import type { Metadata } from "next";
import { Inter } from "next/font/google";
import EventEmitter from "@/components/EventEmitter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AgapeApp | CMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <EventEmitter>
        <body className={inter.className}>{children}</body>
      </EventEmitter>
    </html>
  );
}
